version: 2
jobs:
  build_stg:
    docker:
      - image: circleci/node:8.10
    working_directory: ~/escritorio-pagarme
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-
      - run:
          name: Install dependencies
          command: |
            npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-
      - run:
          name: Deploy application
          command: npm run deploy-site
  build_prd:
    docker:
      - image: circleci/node:8.10
    working_directory: ~/escritorio-pagarme
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-
      - run:
          name: Install dependencies
          command: |
            npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-
      - run:
          name: Deploy application
          command: npm run deploy-site

workflows:
  version: 2
  build_and_deploy:
    jobs:
    - build_stg:
        filters:
          branches:
            ignore: /.*/
          tags:
            only: /^v([0-9]+).([0-9]+).([0-9]+).*$/
    - build_prd:
        filters:
          branches:
            ignore: /.*/
          tags:
            only: /^v([0-9]+).([0-9]+).([0-9]+)$/